### ISSUE TITLE
hiera_writer_files option added to kitchen-puppet

### ISSUE THREAD

**Issue by neillturner** [benwtr/kitchen-puppet-hierawriter#1]
I took the liberty of added the hiera_writer_files option to kitchen-puppet. 
it would be nice to delete your gem (gem yank command) to keep the rubygems list clean but that really up to you.

**Comment by benwtr** [comment]
@neillturner Oh cool, thank you for doing that!

TBH I was planning to ping you to integrate this upstream but I was hoping to first bang it around, maybe find a way to make it work for the `agent` provisioner, rename some things. I probably should have reached out to you first so this didn't happen. ;-)

But it might have been a while before I do that work, so it's actually probably a good thing you went ahead and pulled it in.

I have an open PR in a private repo that is dependant on this thing being a gem. Once it's merged I'll kill the gem. In the meantime I'll add a deprecation notice.

**Comment by benwtr** [comment]
unpublished
